# Generated by Django 3.2 on 2022-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffList',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Delivery Boy', 'Delivery Boy')], max_length=30),
        ),
    ]
