# Generated by Django 3.2 on 2022-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220227_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('weiter', 'weiter'), ('Chef', 'Chef'), ('Delivery Boy', 'Delivery Boy')], max_length=30),
        ),
    ]
