# Generated by Django 3.2 on 2022-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20220227_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingradients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
