# Generated by Django 3.2 on 2022-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_food_ingradients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
