# Generated by Django 3.2 on 2022-04-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20220424_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer')),
                ('food_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.order')),
            ],
        ),
    ]
