# Generated by Django 3.2 on 2022-04-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
