# Generated by Django 3.2 on 2022-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
