# Generated by Django 3.2 on 2022-04-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_order_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
    ]
