# Generated by Django 3.2 on 2022-04-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_order_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='status',
        ),
    ]
