# Generated by Django 3.2 on 2022-04-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_order_food_items'),
        ('hotel', '0016_remove_food_status'),
    ]

    operations = [
    ]
