# Generated by Django 3.2 on 2022-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_merge_20220427_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.TextField(null=True),
        ),
    ]
