# Generated by Django 3.2 on 2022-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_auto_20220427_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
